version: '3.1'

services:

  mart-db:
    container_name: uhafactory-mysql
    image: mysql:5.7
    volumes:
      - ./uhafactory_db:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: uhafactory
    ports:
      - 3306:3306

  redis:
    container_name: uhafactory-redis
    image: redis:alpine
    ports:
      - 6379:6379